// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoltNet.Data;

#nullable disable

namespace VoltNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007133500_AddRealWorldChargingWaitlistAndBlocks")]
    partial class AddRealWorldChargingWaitlistAndBlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoltNet.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_AdminUsers_Username");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_cost");

                    b.Property<decimal?>("AppliedRatePerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("applied_rate_per_kwh");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ChargerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("charger_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal?>("EndMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("end_meter_reading");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<bool>("IsWalkIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_walk_in");

                    b.Property<string>("MeterPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("meter_photo_url");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_id");

                    b.Property<decimal?>("StartMeterReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("start_meter_reading");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Confirmed")
                        .HasColumnName("status");

                    b.Property<decimal?>("UnitsConsumedKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("units_consumed_kwh");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleNumberPlate")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("vehicle_number_plate");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Bookings_CustomerId");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_Bookings_StationId");

                    b.HasIndex("ChargerId", "BookingDate", "Status")
                        .HasDatabaseName("IX_Bookings_Charger_Date_Status");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.Charger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CapacityKw")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("capacity_kw");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("connector_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Chargers", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.ChargingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("connector_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("RatePerHour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rate_per_hour");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rate_per_kwh");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("IX_ChargingRates_StationId");

                    b.ToTable("ChargingRates", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.OwnerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("CancellationAdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_admin_remarks");

                    b.Property<DateTime?>("CancellationProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancellation_processed_at");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plan_id");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StationOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("StationOwnerId");

                    b.ToTable("OwnerSubscriptions", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time")
                        .HasColumnName("closing_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,9)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,9)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time")
                        .HasColumnName("opening_time");

                    b.Property<Guid?>("OwnerSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Stations_City");

                    b.HasIndex("OwnerSubscriptionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Stations_Status");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.StationBlockSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("date")
                        .HasColumnName("block_date");

                    b.Property<Guid?>("ChargerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedByManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_manager_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("remarks");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.HasKey("Id");

                    b.HasIndex("ChargerId");

                    b.HasIndex("CreatedByManagerId");

                    b.HasIndex("StationId", "BlockDate")
                        .HasDatabaseName("IX_StationBlockSlots_Date");

                    b.ToTable("StationBlockSlots", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.StationManager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("CanManageRates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage_rates");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StationManagers_UserId");

                    b.HasIndex("StationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StationManagers_StationId_UserId");

                    b.ToTable("StationManagers", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.StationOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("business_registration_number");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("GSTNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gst_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StationOwners_UserId");

                    b.ToTable("StationOwners", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxManagersPerStation")
                        .HasColumnType("int")
                        .HasColumnName("max_managers_per_station");

                    b.Property<int>("MaxStations")
                        .HasColumnType("int")
                        .HasColumnName("max_stations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_per_month");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.UserMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<Guid>("ChargerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("promoted_at");

                    b.Property<int>("QueuePosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("queue_position");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("status");

                    b.Property<string>("VehicleNumberPlate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vehicle_number_plate");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StationId");

                    b.HasIndex("ChargerId", "BookingDate", "StartTime", "Status")
                        .HasDatabaseName("IX_Waitlist_Charger_Slot");

                    b.ToTable("WaitlistEntries", (string)null);
                });

            modelBuilder.Entity("VoltNet.Models.Booking", b =>
                {
                    b.HasOne("VoltNet.Models.Charger", "Charger")
                        .WithMany()
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.UserMaster", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charger");

                    b.Navigation("Customer");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("VoltNet.Models.Charger", b =>
                {
                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany("Chargers")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("VoltNet.Models.ChargingRate", b =>
                {
                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany("ChargingRates")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("VoltNet.Models.OwnerSubscription", b =>
                {
                    b.HasOne("VoltNet.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.StationOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("StationOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("VoltNet.Models.Station", b =>
                {
                    b.HasOne("VoltNet.Models.OwnerSubscription", "OwnerSubscription")
                        .WithMany("Stations")
                        .HasForeignKey("OwnerSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VoltNet.Models.UserMaster", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerSubscription");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("VoltNet.Models.StationBlockSlot", b =>
                {
                    b.HasOne("VoltNet.Models.Charger", "Charger")
                        .WithMany()
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VoltNet.Models.UserMaster", "CreatedByManager")
                        .WithMany()
                        .HasForeignKey("CreatedByManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charger");

                    b.Navigation("CreatedByManager");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("VoltNet.Models.StationManager", b =>
                {
                    b.HasOne("VoltNet.Models.StationOwner", "CreatedByOwner")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.UserMaster", "User")
                        .WithOne()
                        .HasForeignKey("VoltNet.Models.StationManager", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByOwner");

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltNet.Models.StationOwner", b =>
                {
                    b.HasOne("VoltNet.Models.UserMaster", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VoltNet.Models.UserMaster", "User")
                        .WithOne()
                        .HasForeignKey("VoltNet.Models.StationOwner", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoltNet.Models.WaitlistEntry", b =>
                {
                    b.HasOne("VoltNet.Models.Charger", "Charger")
                        .WithMany()
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.UserMaster", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoltNet.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charger");

                    b.Navigation("Customer");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("VoltNet.Models.OwnerSubscription", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("VoltNet.Models.Station", b =>
                {
                    b.Navigation("Chargers");

                    b.Navigation("ChargingRates");
                });
#pragma warning restore 612, 618
        }
    }
}
